WINDOW_SIZE = (1000, 500)
WINDOW_WIDTH = WINDOW_SIZE[0]
WINDOW_HEIGHT = WINDOW_SIZE[1]
WINDOW_X_MID = WINDOW_WIDTH / 2

CHARACTER_SIZE = (140, 140)

CHARACTER_A = [
    (110, 280),
    (110, 140),
    (110, 0)
]
CHARACTER_B = [
    (750, 350),
    (750, 210),
    (750, 70)
]

CHOCOLATE_SIZE = (50, 50)
CHOC_HEIGHT = CHOCOLATE_SIZE[1]
CHOC_WIDTH = CHOCOLATE_SIZE[0]

CONVEYOR_SEGMENT_LENGTH = 100
NUMBER_OF_CONVEYOR_SEGMENTS = 4
CONVEYOR_LENGTH = NUMBER_OF_CONVEYOR_SEGMENTS * CONVEYOR_SEGMENT_LENGTH
CONVEYOR_PADDING = 10
CONVEYOR_START = WINDOW_X_MID - CONVEYOR_LENGTH / 2
CONVEYOR_END = WINDOW_X_MID + CONVEYOR_LENGTH / 2
CONVEYOR_Y_START = 105
CONVEYOR_Y_SPRITE_START = CONVEYOR_Y_START - CHOC_HEIGHT
CONVEYOR_Y_SPACING = 70
CONVEYOR_SPACE_START = CONVEYOR_START - CONVEYOR_PADDING
CONVEYOR_SPACE_END = CONVEYOR_END + CONVEYOR_PADDING
CONVEYOR_SPRITE_END = CONVEYOR_SPACE_END - CHOC_WIDTH

CONVEYOR_Y = [
   105, 175, 245, 315, 385
]

CONVEYOR_DROP_LEFT = CONVEYOR_START - CHOC_WIDTH
CONVEYOR_DROP_RIGHT = CONVEYOR_END

START_CONVEYOR_LENGTH = 100
START_CONVEYOR_HEIGHT = WINDOW_HEIGHT - 100
START_CONVEYOR_DROP_X = WINDOW_WIDTH - START_CONVEYOR_LENGTH
